sn --> det(G,N),nom(G,N).
sn --> nom(Lusho,Lushox).
det(m,s) --> [el];[un].
det(f,s) --> [la];[una].
det(m,p) --> [los];[unos].
det(f,p) --> [las];[unas].
nom(m,s) --> [gato].
nom(f,s) --> [piedra];[gata].
nom(m,p) --> [gatos].
nom(f,p) --> [piedras];[gatas].
